# mysql数据库账号配置
mysql:
  user: root
  password: qw84265   # 123456 ,  qw84265
  host: localhost    # localhost ,119.23.74.49
  port: 3306
  database: nuu_db
  charset: utf8

# redis账号配置
redis:
  password:          #
  host: localhost    # localhost ,119.23.74.49
  port: 6379


